// --------------------------------------------------------------------------------------------------------------------
// <copyright file="BindingXamlPlatformInfo.DefaultOneWayBindingProperties.Wpf.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace Sundew.Xaml.Optimizations.Bindings.Internal.Xaml
{
    using System;
    using System.Collections.Generic;

    internal partial class BindingXamlPlatformInfo
    {
        private static readonly Lazy<IReadOnlyDictionary<string, IReadOnlyCollection<string>>> DefaultOneWayBindingPropertiesWpf =
                new Lazy<IReadOnlyDictionary<string, IReadOnlyCollection<string>>>(
                    () => new Dictionary<string, IReadOnlyCollection<string>>
                    {
                        {
                            "PresentationFramework|System.Windows.FrameworkContentElement",
                            new[]
                            {
                                "Style",
                                "OverridesDefaultStyle",
                                "Name",
                                "Tag",
                                "Language",
                                "FocusVisualStyle",
                                "Cursor",
                                "ForceCursor",
                                "InputScope",
                                "DataContext",
                                "BindingGroup",
                                "ToolTip",
                                "ContextMenu",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.FrameworkElement",
                            new[]
                            {
                                "Style",
                                "OverridesDefaultStyle",
                                "UseLayoutRounding",
                                "DataContext",
                                "BindingGroup",
                                "Language",
                                "Name",
                                "Tag",
                                "InputScope",
                                "ActualWidth",
                                "ActualHeight",
                                "LayoutTransform",
                                "Width",
                                "MinWidth",
                                "MaxWidth",
                                "Height",
                                "MinHeight",
                                "MaxHeight",
                                "FlowDirection",
                                "Margin",
                                "HorizontalAlignment",
                                "VerticalAlignment",
                                "FocusVisualStyle",
                                "Cursor",
                                "ForceCursor",
                                "ToolTip",
                                "ContextMenu",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.VisualStateManager",
                            new[]
                            {
                                "VisualStateGroups",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Window",
                            new[]
                            {
                                "AllowsTransparency",
                                "Title",
                                "Icon",
                                "SizeToContent",
                                "Top",
                                "Left",
                                "ShowInTaskbar",
                                "IsActive",
                                "WindowStyle",
                                "ResizeMode",
                                "Topmost",
                                "ShowActivated",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Shell.WindowChrome",
                            new[]
                            {
                                "IsHitTestVisibleInChrome",
                                "ResizeGripDirection",
                                "UseAeroCaptionButtons",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Shapes.Line",
                            new[]
                            {
                                "X1",
                                "Y1",
                                "X2",
                                "Y2",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Shapes.Path",
                            new[]
                            {
                                "Data",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Shapes.Polygon",
                            new[]
                            {
                                "Points",
                                "FillRule",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Shapes.Polyline",
                            new[]
                            {
                                "Points",
                                "FillRule",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Shapes.Rectangle",
                            new[]
                            {
                                "RadiusX",
                                "RadiusY",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Shapes.Shape",
                            new[]
                            {
                                "Stretch",
                                "Fill",
                                "Stroke",
                                "StrokeThickness",
                                "StrokeStartLineCap",
                                "StrokeEndLineCap",
                                "StrokeDashCap",
                                "StrokeLineJoin",
                                "StrokeMiterLimit",
                                "StrokeDashOffset",
                                "StrokeDashArray",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Data.CollectionContainer",
                            new[]
                            {
                                "Collection",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Data.CollectionViewSource",
                            new[]
                            {
                                "View",
                                "Source",
                                "CollectionViewType",
                                "CanChangeLiveSorting",
                                "IsLiveSortingRequested",
                                "IsLiveSorting",
                                "CanChangeLiveFiltering",
                                "IsLiveFilteringRequested",
                                "IsLiveFiltering",
                                "CanChangeLiveGrouping",
                                "IsLiveGroupingRequested",
                                "IsLiveGrouping",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Navigation.NavigationWindow",
                            new[]
                            {
                                "SandboxExternalContent",
                                "ShowsNavigationUI",
                                "Source",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.AnchoredBlock",
                            new[]
                            {
                                "Margin",
                                "Padding",
                                "BorderThickness",
                                "BorderBrush",
                                "TextAlignment",
                                "LineHeight",
                                "LineStackingStrategy",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.Block",
                            new[]
                            {
                                "IsHyphenationEnabled",
                                "Margin",
                                "Padding",
                                "BorderThickness",
                                "BorderBrush",
                                "TextAlignment",
                                "FlowDirection",
                                "LineHeight",
                                "LineStackingStrategy",
                                "BreakPageBefore",
                                "BreakColumnBefore",
                                "ClearFloaters",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.DocumentReference",
                            new[]
                            {
                                "Source",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.FixedDocumentSequence",
                            new[]
                            {
                                "PrintTicket",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.Figure",
                            new[]
                            {
                                "HorizontalAnchor",
                                "VerticalAnchor",
                                "HorizontalOffset",
                                "VerticalOffset",
                                "CanDelayPlacement",
                                "WrapDirection",
                                "Width",
                                "Height",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.FixedDocument",
                            new[]
                            {
                                "PrintTicket",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.FixedPage",
                            new[]
                            {
                                "PrintTicket",
                                "Background",
                                "Left",
                                "Top",
                                "Right",
                                "Bottom",
                                "ContentBox",
                                "BleedBox",
                                "NavigateUri",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.Floater",
                            new[]
                            {
                                "HorizontalAlignment",
                                "Width",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.FlowDocument",
                            new[]
                            {
                                "FontFamily",
                                "FontStyle",
                                "FontWeight",
                                "FontStretch",
                                "FontSize",
                                "Foreground",
                                "Background",
                                "TextEffects",
                                "TextAlignment",
                                "FlowDirection",
                                "LineHeight",
                                "LineStackingStrategy",
                                "ColumnWidth",
                                "ColumnGap",
                                "IsColumnWidthFlexible",
                                "ColumnRuleWidth",
                                "ColumnRuleBrush",
                                "IsOptimalParagraphEnabled",
                                "PageWidth",
                                "MinPageWidth",
                                "MaxPageWidth",
                                "PageHeight",
                                "MinPageHeight",
                                "MaxPageHeight",
                                "PagePadding",
                                "IsHyphenationEnabled",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.Glyphs",
                            new[]
                            {
                                "Fill",
                                "Indices",
                                "UnicodeString",
                                "CaretStops",
                                "FontRenderingEmSize",
                                "OriginX",
                                "OriginY",
                                "FontUri",
                                "StyleSimulations",
                                "IsSideways",
                                "BidiLevel",
                                "DeviceFontName",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.Hyperlink",
                            new[]
                            {
                                "Command",
                                "CommandParameter",
                                "CommandTarget",
                                "NavigateUri",
                                "TargetName",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.Inline",
                            new[]
                            {
                                "BaselineAlignment",
                                "TextDecorations",
                                "FlowDirection",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.List",
                            new[]
                            {
                                "MarkerStyle",
                                "MarkerOffset",
                                "StartIndex",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.ListItem",
                            new[]
                            {
                                "Margin",
                                "Padding",
                                "BorderThickness",
                                "BorderBrush",
                                "TextAlignment",
                                "FlowDirection",
                                "LineHeight",
                                "LineStackingStrategy",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.PageContent",
                            new[]
                            {
                                "Source",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.Paragraph",
                            new[]
                            {
                                "TextDecorations",
                                "TextIndent",
                                "MinOrphanLines",
                                "MinWidowLines",
                                "KeepWithNext",
                                "KeepTogether",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.Table",
                            new[]
                            {
                                "CellSpacing",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.TableCell",
                            new[]
                            {
                                "Padding",
                                "BorderThickness",
                                "BorderBrush",
                                "TextAlignment",
                                "FlowDirection",
                                "LineHeight",
                                "LineStackingStrategy",
                                "ColumnSpan",
                                "RowSpan",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.TableColumn",
                            new[]
                            {
                                "Width",
                                "Background",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Documents.TextElement",
                            new[]
                            {
                                "FontFamily",
                                "FontStyle",
                                "FontWeight",
                                "FontStretch",
                                "FontSize",
                                "Foreground",
                                "Background",
                                "TextEffects",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.StickyNoteControl",
                            new[]
                            {
                                "Author",
                                "IsExpanded",
                                "IsActive",
                                "IsMouseOverAnchor",
                                "CaptionFontFamily",
                                "CaptionFontSize",
                                "CaptionFontStretch",
                                "CaptionFontStyle",
                                "CaptionFontWeight",
                                "PenWidth",
                                "StickyNoteType",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.AccessText",
                            new[]
                            {
                                "Text",
                                "FontFamily",
                                "FontStyle",
                                "FontWeight",
                                "FontStretch",
                                "FontSize",
                                "Foreground",
                                "Background",
                                "TextDecorations",
                                "TextEffects",
                                "LineHeight",
                                "LineStackingStrategy",
                                "TextAlignment",
                                "TextTrimming",
                                "TextWrapping",
                                "BaselineOffset",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Border",
                            new[]
                            {
                                "BorderThickness",
                                "Padding",
                                "CornerRadius",
                                "BorderBrush",
                                "Background",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Button",
                            new[]
                            {
                                "IsDefault",
                                "IsCancel",
                                "IsDefaulted",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Calendar",
                            new[]
                            {
                                "FirstDayOfWeek",
                                "IsTodayHighlighted",
                                "SelectionMode",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Canvas",
                            new[]
                            {
                                "Left",
                                "Top",
                                "Right",
                                "Bottom",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ComboBox",
                            new[]
                            {
                                "MaxDropDownHeight",
                                "ShouldPreserveUserEnteredPrefix",
                                "IsEditable",
                                "IsReadOnly",
                                "SelectionBoxItem",
                                "SelectionBoxItemTemplate",
                                "SelectionBoxItemStringFormat",
                                "StaysOpenOnEdit",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ComboBoxItem",
                            new[]
                            {
                                "IsHighlighted",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ContentControl",
                            new[]
                            {
                                "Content",
                                "HasContent",
                                "ContentTemplate",
                                "ContentTemplateSelector",
                                "ContentStringFormat",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ContentPresenter",
                            new[]
                            {
                                "RecognizesAccessKey",
                                "Content",
                                "ContentTemplate",
                                "ContentTemplateSelector",
                                "ContentStringFormat",
                                "ContentSource",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ContextMenu",
                            new[]
                            {
                                "HorizontalOffset",
                                "VerticalOffset",
                                "PlacementTarget",
                                "PlacementRectangle",
                                "Placement",
                                "HasDropShadow",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Control",
                            new[]
                            {
                                "BorderBrush",
                                "BorderThickness",
                                "Background",
                                "Foreground",
                                "FontFamily",
                                "FontSize",
                                "FontStretch",
                                "FontStyle",
                                "FontWeight",
                                "HorizontalContentAlignment",
                                "VerticalContentAlignment",
                                "TabIndex",
                                "IsTabStop",
                                "Padding",
                                "Template",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DataGrid",
                            new[]
                            {
                                "CanUserResizeColumns",
                                "ColumnWidth",
                                "MinColumnWidth",
                                "MaxColumnWidth",
                                "GridLinesVisibility",
                                "HorizontalGridLinesBrush",
                                "VerticalGridLinesBrush",
                                "RowStyle",
                                "RowValidationErrorTemplate",
                                "RowStyleSelector",
                                "RowBackground",
                                "AlternatingRowBackground",
                                "RowHeight",
                                "MinRowHeight",
                                "RowHeaderWidth",
                                "RowHeaderActualWidth",
                                "ColumnHeaderHeight",
                                "HeadersVisibility",
                                "CellStyle",
                                "ColumnHeaderStyle",
                                "RowHeaderStyle",
                                "RowHeaderTemplate",
                                "RowHeaderTemplateSelector",
                                "HorizontalScrollBarVisibility",
                                "VerticalScrollBarVisibility",
                                "IsReadOnly",
                                "CurrentItem",
                                "CurrentColumn",
                                "CurrentCell",
                                "CanUserAddRows",
                                "CanUserDeleteRows",
                                "RowDetailsVisibilityMode",
                                "AreRowDetailsFrozen",
                                "RowDetailsTemplate",
                                "RowDetailsTemplateSelector",
                                "CanUserResizeRows",
                                "NewItemMargin",
                                "SelectionMode",
                                "SelectionUnit",
                                "CanUserSortColumns",
                                "AutoGenerateColumns",
                                "FrozenColumnCount",
                                "NonFrozenColumnsViewportHorizontalOffset",
                                "EnableRowVirtualization",
                                "EnableColumnVirtualization",
                                "CanUserReorderColumns",
                                "DragIndicatorStyle",
                                "DropLocationIndicatorStyle",
                                "ClipboardCopyMode",
                                "CellsPanelHorizontalOffset",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DataGridBoundColumn",
                            new[]
                            {
                                "ElementStyle",
                                "EditingElementStyle",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DataGridCell",
                            new[]
                            {
                                "Column",
                                "IsEditing",
                                "IsReadOnly",
                                "IsSelected",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DataGridCheckBoxColumn",
                            new[]
                            {
                                "IsThreeState",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DataGridColumn",
                            new[]
                            {
                                "Header",
                                "HeaderStyle",
                                "HeaderStringFormat",
                                "HeaderTemplate",
                                "HeaderTemplateSelector",
                                "CellStyle",
                                "IsReadOnly",
                                "Width",
                                "MinWidth",
                                "MaxWidth",
                                "ActualWidth",
                                "DisplayIndex",
                                "SortMemberPath",
                                "CanUserSort",
                                "SortDirection",
                                "IsAutoGenerated",
                                "IsFrozen",
                                "CanUserReorder",
                                "DragIndicatorStyle",
                                "CanUserResize",
                                "Visibility",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DataGridComboBoxColumn",
                            new[]
                            {
                                "ElementStyle",
                                "EditingElementStyle",
                                "ItemsSource",
                                "DisplayMemberPath",
                                "SelectedValuePath",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DataGridHyperlinkColumn",
                            new[]
                            {
                                "TargetName",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DataGridRow",
                            new[]
                            {
                                "Item",
                                "ItemsPanel",
                                "Header",
                                "HeaderStyle",
                                "HeaderTemplate",
                                "HeaderTemplateSelector",
                                "ValidationErrorTemplate",
                                "DetailsTemplate",
                                "DetailsTemplateSelector",
                                "DetailsVisibility",
                                "AlternationIndex",
                                "IsEditing",
                                "IsNewItem",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DataGridTemplateColumn",
                            new[]
                            {
                                "CellTemplate",
                                "CellTemplateSelector",
                                "CellEditingTemplate",
                                "CellEditingTemplateSelector",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DataGridTextColumn",
                            new[]
                            {
                                "FontFamily",
                                "FontSize",
                                "FontStyle",
                                "FontWeight",
                                "Foreground",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DatePicker",
                            new[]
                            {
                                "SelectedDateFormat",
                                "Text",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DefinitionBase",
                            new[]
                            {
                                "SharedSizeGroup",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DockPanel",
                            new[]
                            {
                                "LastChildFill",
                                "Dock",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.DocumentViewer",
                            new[]
                            {
                                "ExtentWidth",
                                "ExtentHeight",
                                "ViewportWidth",
                                "ViewportHeight",
                                "VerticalPageSpacing",
                                "HorizontalPageSpacing",
                                "CanMoveUp",
                                "CanMoveDown",
                                "CanMoveLeft",
                                "CanMoveRight",
                                "CanIncreaseZoom",
                                "CanDecreaseZoom",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.FlowDocumentReader",
                            new[]
                            {
                                "ViewingMode",
                                "IsPageViewEnabled",
                                "IsTwoPageViewEnabled",
                                "IsScrollViewEnabled",
                                "PageCount",
                                "PageNumber",
                                "CanGoToPreviousPage",
                                "CanGoToNextPage",
                                "IsFindEnabled",
                                "IsPrintEnabled",
                                "Document",
                                "Zoom",
                                "MaxZoom",
                                "MinZoom",
                                "CanIncreaseZoom",
                                "CanDecreaseZoom",
                                "SelectionBrush",
                                "SelectionOpacity",
                                "IsSelectionActive",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.FlowDocumentScrollViewer",
                            new[]
                            {
                                "Document",
                                "Zoom",
                                "MaxZoom",
                                "MinZoom",
                                "CanIncreaseZoom",
                                "CanDecreaseZoom",
                                "IsSelectionEnabled",
                                "IsToolBarVisible",
                                "HorizontalScrollBarVisibility",
                                "VerticalScrollBarVisibility",
                                "SelectionBrush",
                                "SelectionOpacity",
                                "IsSelectionActive",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Frame",
                            new[]
                            {
                                "Source",
                                "SandboxExternalContent",
                                "JournalOwnership",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Grid",
                            new[]
                            {
                                "ShowGridLines",
                                "Column",
                                "Row",
                                "ColumnSpan",
                                "RowSpan",
                                "IsSharedSizeScope",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.GridSplitter",
                            new[]
                            {
                                "ResizeDirection",
                                "ResizeBehavior",
                                "ShowsPreview",
                                "PreviewStyle",
                                "KeyboardIncrement",
                                "DragIncrement",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.GridView",
                            new[]
                            {
                                "ColumnHeaderTemplate",
                                "ColumnHeaderTemplateSelector",
                                "AllowsColumnReorder",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.GridViewColumn",
                            new[]
                            {
                                "Header",
                                "HeaderContainerStyle",
                                "HeaderTemplate",
                                "HeaderTemplateSelector",
                                "HeaderStringFormat",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.GridViewColumnHeader",
                            new[]
                            {
                                "Role",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.GridViewHeaderRowPresenter",
                            new[]
                            {
                                "ColumnHeaderContainerStyle",
                                "ColumnHeaderTemplate",
                                "ColumnHeaderTemplateSelector",
                                "ColumnHeaderStringFormat",
                                "ColumnHeaderContextMenu",
                                "ColumnHeaderToolTip",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.GridViewRowPresenter",
                            new[]
                            {
                                "Content",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.HeaderedContentControl",
                            new[]
                            {
                                "Header",
                                "HasHeader",
                                "HeaderTemplate",
                                "HeaderTemplateSelector",
                                "HeaderStringFormat",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.HeaderedItemsControl",
                            new[]
                            {
                                "Header",
                                "HeaderTemplate",
                                "HeaderTemplateSelector",
                                "HeaderStringFormat",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Image",
                            new[]
                            {
                                "Source",
                                "Stretch",
                                "StretchDirection",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.InkCanvas",
                            new[]
                            {
                                "Background",
                                "Top",
                                "Bottom",
                                "Left",
                                "Right",
                                "Strokes",
                                "DefaultDrawingAttributes",
                                "ActiveEditingMode",
                                "EditingMode",
                                "EditingModeInverted",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.InkPresenter",
                            new[]
                            {
                                "Strokes",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ItemsControl",
                            new[]
                            {
                                "ItemsSource",
                                "HasItems",
                                "DisplayMemberPath",
                                "ItemTemplate",
                                "ItemTemplateSelector",
                                "ItemStringFormat",
                                "ItemBindingGroup",
                                "ItemContainerStyle",
                                "ItemContainerStyleSelector",
                                "ItemsPanel",
                                "IsGrouping",
                                "GroupStyleSelector",
                                "AlternationCount",
                                "AlternationIndex",
                                "IsTextSearchEnabled",
                                "IsTextSearchCaseSensitive",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Label",
                            new[]
                            {
                                "Target",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ListBox",
                            new[]
                            {
                                "SelectionMode",
                                "SelectedItems",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.MediaElement",
                            new[]
                            {
                                "Source",
                                "Volume",
                                "Balance",
                                "IsMuted",
                                "ScrubbingEnabled",
                                "UnloadedBehavior",
                                "LoadedBehavior",
                                "Stretch",
                                "StretchDirection",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Menu",
                            new[]
                            {
                                "IsMainMenu",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.MenuItem",
                            new[]
                            {
                                "Command",
                                "CommandParameter",
                                "CommandTarget",
                                "Role",
                                "IsCheckable",
                                "IsPressed",
                                "IsHighlighted",
                                "StaysOpenOnClick",
                                "InputGestureText",
                                "Icon",
                                "IsSuspendingPopupAnimation",
                                "ItemContainerTemplateSelector",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Page",
                            new[]
                            {
                                "Content",
                                "Background",
                                "Title",
                                "Foreground",
                                "FontFamily",
                                "FontSize",
                                "Template",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Panel",
                            new[]
                            {
                                "Background",
                                "IsItemsHost",
                                "ZIndex",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.PasswordBox",
                            new[]
                            {
                                "PasswordChar",
                                "SelectionBrush",
                                "SelectionTextBrush",
                                "SelectionOpacity",
                                "CaretBrush",
                                "IsSelectionActive",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ScrollContentPresenter",
                            new[]
                            {
                                "CanContentScroll",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ProgressBar",
                            new[]
                            {
                                "IsIndeterminate",
                                "Orientation",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.RadioButton",
                            new[]
                            {
                                "GroupName",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.RichTextBox",
                            new[]
                            {
                                "IsDocumentEnabled",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ScrollViewer",
                            new[]
                            {
                                "CanContentScroll",
                                "HorizontalScrollBarVisibility",
                                "VerticalScrollBarVisibility",
                                "ComputedHorizontalScrollBarVisibility",
                                "ComputedVerticalScrollBarVisibility",
                                "VerticalOffset",
                                "HorizontalOffset",
                                "ContentVerticalOffset",
                                "ContentHorizontalOffset",
                                "ExtentWidth",
                                "ExtentHeight",
                                "ScrollableWidth",
                                "ScrollableHeight",
                                "ViewportWidth",
                                "ViewportHeight",
                                "IsDeferredScrollingEnabled",
                                "PanningMode",
                                "PanningDeceleration",
                                "PanningRatio",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.FlowDocumentPageViewer",
                            new[]
                            {
                                "Zoom",
                                "MaxZoom",
                                "MinZoom",
                                "ZoomIncrement",
                                "CanIncreaseZoom",
                                "CanDecreaseZoom",
                                "SelectionBrush",
                                "SelectionOpacity",
                                "IsSelectionActive",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Slider",
                            new[]
                            {
                                "Orientation",
                                "IsDirectionReversed",
                                "Delay",
                                "Interval",
                                "AutoToolTipPlacement",
                                "AutoToolTipPrecision",
                                "IsSnapToTickEnabled",
                                "TickPlacement",
                                "TickFrequency",
                                "Ticks",
                                "IsSelectionRangeEnabled",
                                "IsMoveToPointEnabled",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.SoundPlayerAction",
                            new[]
                            {
                                "Source",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.StackPanel",
                            new[]
                            {
                                "Orientation",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.TabControl",
                            new[]
                            {
                                "TabStripPlacement",
                                "SelectedContent",
                                "SelectedContentTemplate",
                                "SelectedContentTemplateSelector",
                                "SelectedContentStringFormat",
                                "ContentTemplate",
                                "ContentTemplateSelector",
                                "ContentStringFormat",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.TabItem",
                            new[]
                            {
                                "TabStripPlacement",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.TextBlock",
                            new[]
                            {
                                "BaselineOffset",
                                "Text",
                                "FontFamily",
                                "FontStyle",
                                "FontWeight",
                                "FontStretch",
                                "FontSize",
                                "Foreground",
                                "Background",
                                "TextDecorations",
                                "TextEffects",
                                "LineHeight",
                                "LineStackingStrategy",
                                "Padding",
                                "TextAlignment",
                                "TextTrimming",
                                "TextWrapping",
                                "IsHyphenationEnabled",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.TextBox",
                            new[]
                            {
                                "TextWrapping",
                                "MinLines",
                                "MaxLines",
                                "CharacterCasing",
                                "MaxLength",
                                "TextAlignment",
                                "TextDecorations",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.TextSearch",
                            new[]
                            {
                                "TextPath",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ToolBar",
                            new[]
                            {
                                "Orientation",
                                "Band",
                                "BandIndex",
                                "HasOverflowItems",
                                "IsOverflowItem",
                                "OverflowMode",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ToolBarTray",
                            new[]
                            {
                                "Background",
                                "Orientation",
                                "IsLocked",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ToolTip",
                            new[]
                            {
                                "HorizontalOffset",
                                "VerticalOffset",
                                "HasDropShadow",
                                "PlacementTarget",
                                "PlacementRectangle",
                                "Placement",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.TreeView",
                            new[]
                            {
                                "SelectedItem",
                                "SelectedValue",
                                "SelectedValuePath",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.TreeViewItem",
                            new[]
                            {
                                "IsExpanded",
                                "IsSelectionActive",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Viewbox",
                            new[]
                            {
                                "Stretch",
                                "StretchDirection",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Viewport3D",
                            new[]
                            {
                                "Camera",
                                "Children",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.VirtualizingPanel",
                            new[]
                            {
                                "IsVirtualizing",
                                "VirtualizationMode",
                                "IsVirtualizingWhenGrouping",
                                "ScrollUnit",
                                "CacheLength",
                                "CacheLengthUnit",
                                "IsContainerVirtualizable",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.VirtualizingStackPanel",
                            new[]
                            {
                                "IsVirtualizing",
                                "VirtualizationMode",
                                "Orientation",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.WrapPanel",
                            new[]
                            {
                                "ItemWidth",
                                "ItemHeight",
                                "Orientation",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.ColumnDefinition",
                            new[]
                            {
                                "Width",
                                "MinWidth",
                                "MaxWidth",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.RowDefinition",
                            new[]
                            {
                                "Height",
                                "MinHeight",
                                "MaxHeight",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.BulletDecorator",
                            new[]
                            {
                                "Background",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.ButtonBase",
                            new[]
                            {
                                "Command",
                                "CommandParameter",
                                "CommandTarget",
                                "IsPressed",
                                "ClickMode",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.CalendarButton",
                            new[]
                            {
                                "HasSelectedDays",
                                "IsInactive",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.CalendarDayButton",
                            new[]
                            {
                                "IsToday",
                                "IsSelected",
                                "IsInactive",
                                "IsBlackedOut",
                                "IsHighlighted",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.DataGridColumnHeader",
                            new[]
                            {
                                "SeparatorBrush",
                                "SeparatorVisibility",
                                "DisplayIndex",
                                "CanUserSort",
                                "SortDirection",
                                "IsFrozen",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.DataGridRowHeader",
                            new[]
                            {
                                "SeparatorBrush",
                                "SeparatorVisibility",
                                "IsRowSelected",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.DocumentPageView",
                            new[]
                            {
                                "PageNumber",
                                "Stretch",
                                "StretchDirection",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.DocumentViewerBase",
                            new[]
                            {
                                "Document",
                                "PageCount",
                                "MasterPageNumber",
                                "CanGoToPreviousPage",
                                "CanGoToNextPage",
                                "IsMasterPage",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.GridViewRowPresenterBase",
                            new[]
                            {
                                "Columns",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.MenuBase",
                            new[]
                            {
                                "ItemContainerTemplateSelector",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.Popup",
                            new[]
                            {
                                "Child",
                                "Placement",
                                "CustomPopupPlacementCallback",
                                "StaysOpen",
                                "HorizontalOffset",
                                "VerticalOffset",
                                "PlacementTarget",
                                "PlacementRectangle",
                                "PopupAnimation",
                                "AllowsTransparency",
                                "HasDropShadow",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.RangeBase",
                            new[]
                            {
                                "Minimum",
                                "Maximum",
                                "LargeChange",
                                "SmallChange",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.RepeatButton",
                            new[]
                            {
                                "Delay",
                                "Interval",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.ScrollBar",
                            new[]
                            {
                                "Orientation",
                                "ViewportSize",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.SelectiveScrollingGrid",
                            new[]
                            {
                                "SelectiveScrollingOrientation",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.Selector",
                            new[]
                            {
                                "IsSelectionActive",
                                "IsSynchronizedWithCurrentItem",
                                "SelectedValuePath",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.StatusBar",
                            new[]
                            {
                                "ItemContainerTemplateSelector",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.TextBoxBase",
                            new[]
                            {
                                "IsReadOnly",
                                "IsReadOnlyCaretVisible",
                                "AcceptsReturn",
                                "AcceptsTab",
                                "HorizontalScrollBarVisibility",
                                "VerticalScrollBarVisibility",
                                "IsUndoEnabled",
                                "UndoLimit",
                                "AutoWordSelection",
                                "SelectionBrush",
                                "SelectionTextBrush",
                                "SelectionOpacity",
                                "CaretBrush",
                                "IsSelectionActive",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.Thumb",
                            new[]
                            {
                                "IsDragging",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.TickBar",
                            new[]
                            {
                                "Fill",
                                "Minimum",
                                "Maximum",
                                "SelectionStart",
                                "SelectionEnd",
                                "IsSelectionRangeEnabled",
                                "TickFrequency",
                                "Ticks",
                                "IsDirectionReversed",
                                "Placement",
                                "ReservedSpace",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.ToggleButton",
                            new[]
                            {
                                "IsThreeState",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.ToolBarOverflowPanel",
                            new[]
                            {
                                "WrapWidth",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.Track",
                            new[]
                            {
                                "Orientation",
                                "Minimum",
                                "Maximum",
                                "ViewportSize",
                                "IsDirectionReversed",
                            }
                        },
                        {
                            "PresentationFramework|System.Windows.Controls.Primitives.UniformGrid",
                            new[]
                            {
                                "FirstColumn",
                                "Columns",
                                "Rows",
                            }
                        },
                    });
    }
}